### ISSUE TITLE
Allow group argument in "ifHasRole" signature

### ISSUE THREAD

**Issue by jbbr** [ongoworks/meteor-security#11]
The "alanning:roles" package allows to check permission by group since version 1.1.0.
It would be great to be able to use the "userIsInRole(user, roles, group)" signature from meteor-security.

e.g:

```javascript
Posts.permit('remove').ifHasRole('admin', 'company1.com').apply();
```

or even in array syntax:
```javascript
Posts.permit('remove').ifHasRole(['admin', 'posts-admin'], 'company1.com').apply();
```

**Comment by aldeed** [comment]
Implemented with object arg since we only support a single arg. See updated docs: https://github.com/ongoworks/meteor-security#built-in-rule-chain-methods
