### ISSUE TITLE
how to use dynamic role with security?

### ISSUE THREAD

**Issue by yuomtheara** [ongoworks/meteor-security#14]
For example I have 2 user like:
```
// user 1
username: 'test1'
user.roles = ['post.insert']

// user 2
username: 'test2'
user.roles = ['post.insert', 'post.update']
```
So I need to pass dynamic variable to role on security via user log in.
```
// Check user role
var role = .........
Posts.permit('remove').ifHasRole({role: role}).apply();
```
How to solve?

**Comment by aldeed** [comment]
The built-in `ifHasRole` is for simple checks. You will have to write your own rule method with the checks you need. You can copy the [built-in one](https://github.com/ongoworks/meteor-security/blob/master/security-rules.js#L49-L62) and change its name and change it to do what you need.
