### ISSUE TITLE
Could i use meteor-security in meteor method?

### ISSUE THREAD

**Issue by yuomtheara** [ongoworks/meteor-security#15]
Could i use meteor-security in meteor method like this:
```
Meteor.method({
   myMethod: function(roles) {
   Posts.permit('remove').ifHasRole({role: roles}).apply();
   }
});
```
And then we call it before insert or after submit.

**Comment by aldeed** [comment]
No it is a substitute for allow/deny, so it applies to client-side insert/update/remove calls only.

**Comment by johngonzalez** [comment]
The other hand. Could i use meteor-security in meteor method like this:
``` javascript
// In server/security.js
Posts.permit('remove').ifHasRole('admin').apply();

// In server/methods.js
Meteor.method({
   myMethod: function(post) {
     Post.insert(post);
   }
});
```

**Comment by aldeed** [comment]
If you add the [dispatch:run-as-user](https://github.com/DispatchMe/Meteor-run-as-user) package, you can use `Meteor.runRestricted` to apply allow/deny rules in server code such as a method:

```js
Meteor.method({
   myMethod: function(post) {
     Meteor.runRestricted(function() {
       Post.insert(post);
     });
   }
});
```

I'm also working on an enhancement to this pkg to provide direct server support.
