### ISSUE TITLE
How to unit test permit rules?

### ISSUE THREAD

**Issue by guysmoilov** [ongoworks/meteor-security#16]
Hi, I wondered if anyone has had success in writing unit tests to confirm the behavior of the permit rules in their app.

I tried to follow the instructions here: http://stackoverflow.com/questions/28226969/testing-meteor-testing-allow-deny-with-a-unit-test-instead-of-integration-te
But it doesn't seem to work, I get undefined Docs._velocityAllow/Deny, and besides, I don't even know if that method is conceptually right for permit rules.
I should mention that I also use aldeed:collection2, which I think also adds its own allow rules.

Of course, I did manage to write integration tests for this, but by their nature they are very destructive (insert/update/remove actions...). They interfered with the other tests, so currently I just put them last in my test order.

So, does anyone know of a way to do this in unit or non-destructive integration tests?

**Comment by aldeed** [comment]
Insert checking, for example, is here: https://github.com/meteor/meteor/blob/devel/packages/mongo/collection.js#L955-L979

As you can see, it's not separate from the actual `insert` call, so you can't unit test it directly. (You could submit an issue to the Meteor repo asking them to separate and export the new function.)

One option might be to use https://atmospherejs.com/practicalmeteor/sinon to create a stub for `testCollection._collection.insert`, then test `_validatedInsert`, then restore the stub.
