### ISSUE TITLE
Conflict with Mongol / mongo-collection-instances

### ISSUE THREAD

**Issue by msavin** [ongoworks/meteor-security#23]
Hey folks,

I'm wondering if you can help with an issue one of the Mongol users has been having. I think the conflict stems from Mongol depending on <a href="https://github.com/dburles/mongo-collection-instances">dburles/mongo-collection-instances</a>, which wraps Mongo.Collection. I'm wondering your package can somehow accommodate for that? 

More details here:
 - https://github.com/msavin/Mongol/issues/49

**Comment by aldeed** [comment]
@msavin, mongo-collection-instances relies on lai:collection-extensions, which I believe @rclai created to avoid this very issue. Peculiar.

We can pretty easily stop throwing the error, but a more proper solution would be nice.

**Comment by aldeed** [comment]
Not a bug in this package. Closing.
