### ISSUE TITLE
Update for heroku platform

### ISSUE THREAD

**Issue by jackkav** [ongoworks/meteor-security#25]
taken from heroku log  
     => Errors while initializing project:

       While checking for ongoworks:security@1.2.0:
       error: No compatible binary build found for this package. Contact the package
       author and ask them to publish it for your platform.

**Comment by aldeed** [comment]
I can't think of any reason why this package would require building for multiple servers. It's fairly simple and doesn't depend on any binary npm packages.

**Comment by aldeed** [comment]
@aaronjudd did you get the notice about needing to build for all architectures when you published the last release?

**Comment by aaronjudd** [comment]
no, no notice.  I was expecting that, but I don't always get one unless I have NPM in the package.

**Comment by aaronjudd** [comment]
`meteor show ongoworks:security --ejson` shows 
```
  "versions": [
    {
      "exports": [],
      "implies": [],
      "name": "ongoworks:security",
      "version": "1.0.0",
      "summary": "Logical security for client-originated MongoDB collection operations",
      "git": "https://github.com/ongoworks/meteor-security.git",
      "publishedBy": "ongoworks",
      "publishedOn": {
        "$date": 1415225784503
      },
      "installed": false,
      "architecturesOS": [
        "os"
      ]
    },

```

which I presume means "all OS" because when you build each machine it gets a listing in the `architecturesOS` object.
