### ISSUE TITLE
Set the website of this GitHub repo to the Atmopshere package

### ISSUE THREAD

**Issue by dandv** [ongoworks/meteor-security#26]
Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by aldeed** [comment]
@aaronjudd Apparently I don't have the security for this so I'll let you do it.

**Comment by aaronjudd** [comment]
so we want the new name to be ongoworks/security?

**Comment by aaronjudd** [comment]
Set to https://atmospherejs.com/ongoworks/security
