### ISSUE TITLE
enable editing only for `profile` field in User document

### ISSUE THREAD

**Issue by achtan** [ongoworks/meteor-security#27]
Hi, how to enable editing only for `profile` field in User document?

this is not working
`Users.permit(['update']).onlyProps('profile').ifOwner().apply();`

**Comment by aldeed** [comment]
What do you mean by "not working"?

What is the definition for `ifOwner`?

I'm assuming you aliased `Meteor.users` as `Users`?

**Comment by achtan** [comment]
yes, `Users = Meteor.users`
`ifOwner` is ok
i got permission denied when i am editing property of `profile` object for example `profile.firstName`

**Comment by aldeed** [comment]
You may have to use the `Security.permit` syntax:

```js
Security.permit(['update']).collections([ Meteor.users ]).onlyProps('profile').ifOwner().apply();
```

Or trying putting the security pkg before the accounts packages in .meteor/packages.

Also, the security you're trying to define is the default security that the accounts package sets up, so technically there should be no need to do it again, though it should work.

**Comment by achtan** [comment]
thx, man ill try it!
