### ISSUE TITLE
Provide client side stub for permit

### ISSUE THREAD

**Issue by rclai** [ongoworks/meteor-security#28]
I know that allow deny rules only work on the server but they can be written isomorphically without incurring an error on the client. The permit method here does throw in the client. Now and again I have experienced having to figure out why the permit method isn't working, thinking there was some kind of package conflict only to find out hours later that it's because it only works on the server.

**Comment by aldeed** [comment]
Client side stubs added by https://github.com/ongoworks/meteor-security/commit/4a4c0ba523b035915a715ec377f2e985c874622b in 1.3.0. Should work fine in common code now.
