### ISSUE TITLE
TypeError: Object #<SecurityRuleConstructor> has no method 'ifHasRole'

### ISSUE THREAD

**Issue by MichaelJCole** [ongoworks/meteor-security#32]
I was getting this error using Meteor's default role system.

`TypeError: Object #<SecurityRuleConstructor> has no method 'ifHasRole'`

See #31 for a PR

**Comment by aaronjudd** [comment]
@MichaelJCole still valid?

**Comment by MichaelJCole** [comment]
Oh hey, no.  I forgot to close this.  Thanks!  

I didn't understand from the docs that the reason helpers functions required the other module.

**Comment by MichaelJCole** [comment]
Autocorrect!  Reason = role.
