### ISSUE TITLE
How to express this security setup?

### ISSUE THREAD

**Issue by MichaelJCole** [ongoworks/meteor-security#33]
ifMine() checks if the current user's id is in that field.  

Here 'ownerId' is the user that created the document.  'subjectId' is who the document is about.  Owners and Subjects can access different fields.  

A user can create a doc about themselves, in which case they are Owner and Subject.  I'm having trouble expressing security settings for that case.

This doesn't work, and I get 403's when saving a Subject+Expert doc.
```
// Tried adding this but still got 403's
Expertises.permit(['update'])
  .ifMine('ownerId')
  .ifMine('subjectId')
  .onlyProps(['justForOwners', 'justForSubjects'])
  .apply();
// Tried just these two first.  Didn't work.
Expertises.permit(['update'])
  .ifMine('ownerId')
  .onlyProps(['justForOwners'])
  .apply();
Expertises.permit(['update'])
  .ifMine('subjectId')
  .onlyProps(['justForSubjects'])
  .apply();
```

How would you express this?

**Comment by aldeed** [comment]
Your definitions seem correct. Are you able to post a link to an app repo with a simple reproduction of this, including the `update` call that fails? That will make it easier to debug.

If the `onlyProps` is causing problems, you might be able to work around whatever the issue is by adding `.ifNotMine()` to the bottom two, for the other property. That way only one rule will apply to each situation.

**Comment by MichaelJCole** [comment]
Hi, the ifNotMine() is a good suggestion.  I tried it, but was still
getting 403 errors.

I'm in a crunch, but will need to circle back to this sooner or later.
I'll post a followup then.  Thanks again for the help :-)

On Sun, Oct 4, 2015 at 9:04 PM, Eric Dobbertin <notifications@github.com>
wrote:

> Your definitions seem correct. Are you able to post a link to an app repo
> with a simple reproduction of this, including the update call that fails?
> That will make it easier to debug.
>
> If the onlyProps is causing problems, you might be able to work around
> whatever the issue is by adding .ifNotMine() to the bottom two, for the
> other property. That way only one rule will apply to each situation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ongoworks/meteor-security/issues/33#issuecomment-145411407>
> .
>



-- 
Michael Cole
http://Powma.com

**Comment by MichaelJCole** [comment]
Hey, thanks for this.  The ifNotMine() suggestion is a good one.  I'm in a crunch time, but will come back to this to reproduce it.

IFWIW, here's my ifMine() function: 
```
Security.defineMethod('ifMine', {
  deny: function (type, arg, userId, doc) {
    var idField = arg || 'ownerId';
    if (! userId) return false;
    return userId !== doc[idField];
  }
});
```

**Comment by aldeed** [comment]
If this is still an issue, please open a new issue with a link to a simple reproduction app.

**Comment by MichaelJCole** [comment]
Hi, this was caused by an incorrect onlyProps() list...  Thanks for the help :-)
