### ISSUE TITLE
connection inside defined method

### ISSUE THREAD

**Issue by dr-dimitru** [ongoworks/meteor-security#35]
Is there any chance to get `this.connection.id` inside `deny` function of defined method?
As we easily can do in Meteor's `methods` and `publish`
[reference](http://docs.meteor.com/#/full/method_connection)

**Comment by aldeed** [comment]
Assuming you're using `Security.can`, you'd just have to pass it to your insert/update/remove function. Everything you pass in is forwarded. So this could be at the top of your method.

```js
Security.can(this.userId).insert(doc, this.connection.id).for(myCollection).throw();
```

But if you mean for a client-initiated action that runs through allow/deny, then no, there isn't a way without changes to core Meteor packages.
