### ISSUE TITLE
Defined method's doc is not fetched when using Security.can()

### ISSUE THREAD

**Issue by ubald** [ongoworks/meteor-security#36]
When using Security.can() inside a Meteor method and implementing a custom Security.defineMethod(), the deny's function doc argument is the id passed to Security.can(this.userId).update(id, modifier)...

Either this is the expected behavior and the documentation should reflect this or it should be implemented and is a bug.

Thanks!

**Comment by aldeed** [comment]
Fixed in 2.0: https://github.com/ongoworks/meteor-security#summary-of-changes-in-20

**Comment by ubald** [comment]
Thanks!
