### ISSUE TITLE
Conflict with matb33:meteor-collection-hooks prevents startup

### ISSUE THREAD

**Issue by haraldronge** [ongoworks/meteor-security#39]
When uninstalling either ongoworks:security or matb33:meteor-collection-hooks problem is solved and server starts up.
Funnily enough with msavin:mongol (unrelated!) installed the conflict goes unnoticed! Only once you deploy to production (mongol being debugonly) the conflict surfaces.

W20160312-16:23:21.509(1)? (STDERR) Error: The collections argument must be a Mongo.Collection instance or an array of them
W20160312-16:23:21.510(1)? (STDERR)     at packages/ongoworks_security/lib/server/security-api.js:67:1

**Comment by aaronjudd** [comment]
we use the package with meteor-collection-hooks and haven't been able to replicate this.  Perhaps load order? Are you installing in the application, or as a package dependency?

**Comment by aldeed** [comment]
This has to do with the way pkgs like collection-hooks override `Mongo.Collection`, which distorts the `instanceof` checks. It's not an issue with this package. You might be able to resolve it by putting collection-hooks AFTER this package in the Meteor packages file, but not necessarily.
