### ISSUE TITLE
Compatibility with CollectionFS

### ISSUE THREAD

**Issue by fusepilot** [ongoworks/meteor-security#4]
````Images```` is an FS.Collection.

````Images.permit(['insert']).apply()```` throws ````TypeError: Object #<EventEmitter> has no method 'permit'````. No surprise since Images is not a ````Mongo.Collection````.
````Images.files.permit(['insert']).apply()```` seems to work. 
````Images.files.permit(['download']).apply()```` throws ````TypeError: Cannot convert null to object````.

It would be great to be able to use these packages together in some fashion.

**Comment by grsabreu** [comment]
Same problem with me

**Comment by grsabreu** [comment]
That seems to occurs when is passed an method that doesn't are one of these 'insert', 'remove', 'update' to .permit()

**Comment by aldeed** [comment]
We could try to make it work with extended like "download" eventually.

**Comment by grsabreu** [comment]
@fusepilot By now, this code had worked for me:
```javascript
Images.files.permit(['insert', 'update', 'remove']).ifHasRole('admin').apply();

Images.allow({
	download: function(userId, doc){
		return true;
	}
});
```

**Comment by aldeed** [comment]
See updated docs: https://github.com/ongoworks/meteor-security#using-with-collectionfs

**Comment by grsabreu** [comment]
Great! :D

**Comment by boboci9** [comment]
Hi,

For my image collection this line:
ShopMediaFiles.files.permit(['download']).ifLoggedIn().apply();
still returns the following error:
TypeError: Cannot convert null to object
Can you tell me what am I doing wrong?

This line works perfectly: ShopMediaFiles.files.permit(['insert', 'update', 'remove']).ifHasRole('admin').apply();

Thanks.
