### ISSUE TITLE
Can Read?

### ISSUE THREAD

**Issue by drewmoore** [ongoworks/meteor-security#40]
Hi, I'm not sure if this needs to be an issue or if I'm missing something. Is there any way to set the permission of `Collection.permit('read')` and reference the permission in `Security.can(userId).read(Collection)`? Thanks.

**Comment by aaronjudd** [comment]
something like `Security.defineMethod("read", { <your logic here > });`?

**Comment by drewmoore** [comment]
Ok, I'll give that a shot. Thank you.

**Comment by aldeed** [comment]
I added support for reads in 2.0: https://github.com/ongoworks/meteor-security#summary-of-changes-in-20

**Comment by drewmoore** [comment]
:+1: :+1:
