### ISSUE TITLE
Document is inserted then removed

### ISSUE THREAD

**Issue by xoxkontrol** [ongoworks/meteor-security#44]
This condition is true -> if( Security.can( this.userId ) .insert( Document )  .for( collection ).check() === true) For which the document is inserted but running collection.find().fetch() on the server the collection is empty it seems like it is deleted where am i goin wrong here

**Comment by aldeed** [comment]
You would need to post reproduction code in order to debug this, but one possibility is that your insert is being rejected by mongo and you are swallowing the error somewhere.
