### ISSUE TITLE
setOnInsert not allowed in a restricted collection

### ISSUE THREAD

**Issue by KoenLav** [ongoworks/meteor-security#48]
simpl-schema makes use of setOnInsert for defaultValue: https://github.com/aldeed/node-simple-schema/blob/3eca0e858ba318d4764d3dea29380c8555531159/lib/SimpleSchema.js#L754

Is there any way to allow this?

Context: https://github.com/aldeed/meteor-autoform/issues/1582

**Comment by aldeed** [comment]
This package is no longer being updated or supported by Reaction.
