### ISSUE TITLE
Security issue with update and remove

### ISSUE THREAD

**Issue by vfonic** [ongoworks/meteor-security#51]
Let's say I follow [Example 1](https://github.com/reactioncommerce/meteor-security#example-1) from the Readme:

```js
Posts.permit(['insert', 'update']).ownsDocument('ownerId');
```

I want only user who created the post to be able to update it.

How would I check it in meteor's `'posts.update'` method?

If I do:

```js
'posts.update'(post) {
  Security.can(this.userId).update(post).for(Posts).throw();
  return Posts.update({ _id: post._id }, { $set: post });
}
```

This should work, right?
Except for the most malicious case when attacker sends this kind of post document:
```js
Meteor.call('posts.update', {
  _id: 'someIdAttackerDoesNotOwn',
  ownerId: 'attackerId'
});
```

The above security check will pass and attacker will successfully change ownerId to his own id.

Same goes for remove check. It would pass and attacker would succeed to remove a record he doesn't own.

Let's say we want to fix this by always providing only `post._id` to update method.
This could work, but only if we allow users to modify all the post's fields (even fields like `"visible"`, `"createdAt"`, `"featured"`, `"commenterIds"`, etc.

The only solution, if we wanted to use `onlyProps` and `ownsDocument` would be to have two if checks:

```js
'posts.update'(post) {
  // fetch post from db and check user can change it (he can't provide fake ownerId)
  !Security.can(this.userId).update(post._id).for(Posts).throw();
  // check user is authorized to update all fields he's trying to update
  !Security.can(this.userId).update(post).for(Posts).throw();
  return Posts.update({ _id: post._id }, { $set: post });
}
```

Am I missing something?

Should this be added as a warning to the documentation?

EDIT: If I'd have even more complicated case, even this wouldn't work.
Let's say I'm an attacker and I have an e-commerce website on Meteor SaaS e-commerce platform. Let's call it `Meterify`. Meterify has an order document model:

```js
order: {
  paymentStatus: ['pending', 'paid', ...],
  shipmentStatus: ['pending', 'shipped', ...]
}
```

When I receive a new order, in administration panel, I can capture payment (which will, if everything goes well, charge customer and change the `paymentStatus` from `'pending'` to `'paid'`).

Here are hypothetical Meterify's security rules:

```js
Orders.permit('update').ifShopOwner().ifPaymentPending().onlyProps('paymentStatus');
// we want to prevent shop owners from reverting payment status to `'pending'`,
// to possibly capture payments multiple times, when they are updating shipment status:
Orders.permit('update').ifShopOwner().ifShipmentPending().onlyProps('shipmentStatus');
```

Let's say there's this order in the db:

```js
order: {
  _id: '1234567890',
  paymentStatus: 'paid',
  shipmentStatus: 'pending'
}
```

I could still call `'orders.update'` and revert payment status to `'pending'` like this:

```js
Meteor.call('posts.update', {
  _id: '1234567890',
  paymentStatus: 'pending'
}
```

Both of the above checks will pass and I'll be able to collect payment again.

This is just one example where user can modify certain document fields only at document's (or user's) certain state. Another possible example that comes to mind would be in an online game:

```js
Fleet.permit('update').ifNotOnAMission().onlyProps('equipment');
Fleet.permit('update').ifOnAMission().onlyProps('directions');
```

Am I still making sense? :)

What do you suggest would be the easiest solution?
I think it would require to be able to do checks on the original db object:

```js
Security.defineMethod('ifNotOnAMission', {
  fetch: [],
  transform: null,
  allow(type, arg, userId, doc, originalDoc) {
    return originalDoc.isOnAMission === false;
  },
});
```

**Comment by aldeed** [comment]
@vfonic I might have got lost somewhere in there, but you are correct that `.update(post)` is NOT the correct secure way to do it. The documentation says to pass in the ID or the current document if you already have it, and NOT something that you THINK might be the current document coming from an untrusted client.

Possibly you are confused in thinking that the first argument to `update` is the one checked for `onlyProps`, but actually it is the second argument, the modifier you will use. So you want:

```js
const modifier = { $set: _.omit(post, '_id') };
Security.can(this.userId).update(post._id, modifier).for(Posts).throw();
return Posts.update(post._id, modifier);
```

**Comment by vfonic** [comment]
Aaaaaah, didn't know there's the modifier argument! That makes things easier. Thanks!
