### ISSUE TITLE
Question about more than one rule to the same collection

### ISSUE THREAD

**Issue by almogdesign** [ongoworks/meteor-security#7]
If I have the following rules setup and lets the first one pass but the second does not, does it stop the insert from happing? Or if just one passes it still runs? 

Posts.permit('insert').ifLoggedIn().apply();
Posts.permit('insert').ifHasRole('admin').apply();

**Comment by aldeed** [comment]
Rules within the same chain combine with AND. Multiple chains for the same collection combine with OR.

**Comment by almogdesign** [comment]
So to be clear with my example it would pass. How are rules with the same chain created?

**Comment by aldeed** [comment]
See the new [Logic section](https://github.com/ongoworks/meteor-security#logic) I added. Does that help clarify?

**Comment by almogdesign** [comment]
yes very clear now thanks
